### ISSUE TITLE
TestAdapter logs to hardcoded file paths

### ISSUE THREAD

**Issue by akamsteeg** [Sellorio/JazSharp#7]
I was just browsing through the source and noticed that the `TestExecutor` in JazSharp.TestAdapter logs to hardcoded file paths when an error occurs:

https://github.com/Sellorio/JazSharp/blob/d878e75a69d360f7cf299e5469bdce7d607093ac/JazSharp.TestAdapter/TestExecutor.cs#L47

https://github.com/Sellorio/JazSharp/blob/d878e75a69d360f7cf299e5469bdce7d607093ac/JazSharp.TestAdapter/TestExecutor.cs#L61

https://github.com/Sellorio/JazSharp/blob/d878e75a69d360f7cf299e5469bdce7d607093ac/JazSharp.TestAdapter/TestExecutor.cs#L92

I think this is undesirable, since it results in polluting the user's file system. Also (have not verified this) I can imagine that a non-elevated user cannot arbitrarily create new folders in the user profile directory.

**Comment by Sellorio** [comment]
Good catch. It was just there for some debugging. It would fail on other people's machine since their username won't be seamillo.

**Comment by Sellorio** [comment]
Fixed in commit https://github.com/Sellorio/JazSharp/commit/ab2ea6a1e8091d84af0f3f3e8b958b1b835f2716
