### ISSUE TITLE
No license associated with the repo

### ISSUE THREAD

**Issue by akamsteeg** [Sellorio/JazSharp#8]
I noticed that there's no license associated with the repository or mentioned in the readme. Right now, contributing or forking puts people in legally questionable waters. Maybe it's a good idea to add a license?

**Comment by Sellorio** [comment]
There is a license that can be found in the JazSharp folder. Not sure how to set it on the project.

**Comment by akamsteeg** [comment]
There's some guidance in the GitHub Help for this: https://help.github.com/en/articles/adding-a-license-to-a-repository Maybe this helps?

**Comment by Sellorio** [comment]
Fixed in commit https://github.com/Sellorio/JazSharp/commit/25647c0cf9b3f80923e632dd164e079d641496da

**Comment by Sellorio** [comment]
Thanks for the help :)
